# server config
server:
  port: 19090


spring:
# datasource
  datasource:
    url: jdbc:log4jdbc:sqlserver://192.168.1.218;databaseName=LCMS
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:sqlserver://192.168.1.218;databaseName=LCMS
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ldcc
    password: ldcc
mybatis:
    type-aliases-package: com.jisoon.model
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
    mapper-locations: classpath:query/*.xml

logbook:
    exclude:
        - /health
        - /admin/**
        - /console/**
    filter.enabled: true
    format.style: http
    obfuscate:
        headers:
            - Authorization
            - X-Secret
        parameters:
            - access_token
            - password
#    write:
#        category: http.wire-log
#        level: INFO
#        chunk-size: 1000
